name: Ejercicio1

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v5

      - name: Instalar pytest
        run: pip install pytest

      - name: Ejecutar tests
        run: pytest test.py
